### ISSUE TITLE
Enhancement: Add hover effect to the login window div for better user interaction

### ISSUE THREAD

**Issue by sanchitc05** [GVishnudhasan/NoDueProject#104]
**Description:**
Hello,

I noticed that the current login window design on the *NoDueProject* website appears static, which might make it less engaging for users. I would like to suggest adding a hover effect to the login window div to make the interface feel more dynamic and interactive. This small change could help capture users' attention and improve their overall experience on the website.

If this sounds good, I’d be happy to implement the hover effect and contribute to the project.

Here's the screenshot of the part I'm talking about

![Screenshot (231)](https://github.com/user-attachments/assets/cc2c0060-9804-4a03-8783-675563aa8e5e)

Looking forward to your feedback!

Best regards,  
Sanchit

**Comment by naitikhoriya1** [comment]
I noticed that the current design of the login window on the NoDueProject website appears static, which might make it less engaging for users. I’d like to suggest adding a subtle hover effect to the login window div. @naitikhoriya1

**Comment by sanchitc05** [comment]
@GVishnudhasan Can you please add hactoberfest label as well

**Comment by sanchitc05** [comment]
@GVishnudhasan please check my response and merge it. If you have any doubts regarding it kindly let me know.
