### ISSUE TITLE
Removing repeated title Nodueissue

### ISSUE THREAD

**Issue by PoojaKanagaraj06** [GVishnudhasan/NoDueProject#109]
![image](https://github.com/user-attachments/assets/97dd519e-de68-4bec-9fdc-72e4e29a60b1)
NoDueSystem title above login form can be suggested to remove as it is at top of the page ,being repeated again
Kindly assign the work to me @GVishnudhasan

**Comment by GVishnudhasan** [comment]
REMOVE THE NAVBAR ALSO, IT SHOULD DISPLAY ONLY UPON LOGIN. @PoojaKanagaraj06

**Comment by PoojaKanagaraj06** [comment]
@GVishnudhasan  can you pls explain once  you said "REMOVE THE NAVBAR ALSO, IT SHOULD DISPLAY ONLY UPON LOGIN"

**Comment by PoojaKanagaraj06** [comment]
@GVishnudhasan  how can i check it will display upon login as I dont have any login credentials

**Comment by GVishnudhasan** [comment]
Try gvishnud10@gmail.com password

**Comment by PoojaKanagaraj06** [comment]
Okay  @GVishnudhasan password pls..

**Comment by GVishnudhasan** [comment]
Email: gvishnud10@gmail.com 
Password: password

**Comment by PoojaKanagaraj06** [comment]
@GVishnudhasan okay I will complete it.

**Comment by PoojaKanagaraj06** [comment]
@GVishnudhasan I am facing lots of error ,after debugging these errors , Successfully the nav bar isnt displaying in index page but login is becomming failed ,I am facing error on login.also i have removed the extra NoDueSystem , can you help with the issue.
