### ISSUE TITLE
Role-Based Access Control:

### ISSUE THREAD

**Issue by Mallik-vinukonda** [GVishnudhasan/NoDueProject#112]
Issues: The system might not have proper user authentication or role-based access, allowing anyone to view or modify data.
Enhancements:
Implement role-based access control (RBAC) to differentiate between admins and regular users (e.g., students). Admins can manage all dues, while students can view and pay their specific dues.
Add a login/signup system with proper authentication and user management

**Comment by GVishnudhasan** [comment]
already implemented
