### ISSUE TITLE
[FEATURE] Add a new page to display all contributors ⭐

### ISSUE THREAD

**Issue by Subhajit-2023-44** [GVishnudhasan/NoDueProject#132]
I want to add a page to showcase all the contributors of this website.

@GVishnudhasan  please assign me this task.

![image](https://github.com/user-attachments/assets/24fd2407-32da-4f69-8fe9-2a66caa0c8ff)

**Comment by Subhajit-2023-44** [comment]
@GVishnudhasan

**Comment by GVishnudhasan** [comment]
It is not needed.
