### ISSUE TITLE
Dynamic Messages 

### ISSUE THREAD

**Issue by prateek2102** [GVishnudhasan/NoDueProject#18]
To improve maintainability and consistency across the codebase, I propose creating a const.js file that will store all dynamic messages. This will centralize messages, making them easier to manage, update, and reference across the application. By exporting these constants, we can avoid hardcoding messages throughout the code, leading to cleaner, more maintainable code.

Proposed Solution:
Create a const.js file that exports all dynamic messages.
Ensure these messages are categorized for easy identification (e.g., errors, success messages, warnings, etc.).
Replace hardcoded messages across the codebase with their corresponding constant references from const.js.
Add a detailed README section explaining how to use and add new messages to the file.
Benefits:
Enhances maintainability by reducing duplication of messages.
Simplifies future updates to messages.
Encourages consistency in messaging throughout the codebase.
Impact:
Refactors all existing dynamic message usages to reference the new const.js file.

**Comment by prateek2102** [comment]
Reference -
![Screenshot from 2024-10-02 14-46-21](https://github.com/user-attachments/assets/08bcede9-6d04-40af-8372-d443ff24348b)

**Comment by prateek2102** [comment]
@GVishnudhasan please assign this to me, i would like to work on it

**Comment by GVishnudhasan** [comment]
Assigned @prateek2102. Good luck.

**Comment by prateek2102** [comment]
Hi @GVishnudhasan , please add a label of level too to it  :) , level1,2,3 whichever
