### ISSUE TITLE
Improve Banner Quality

### ISSUE THREAD

**Issue by AswaniBolisetti** [GVishnudhasan/NoDueProject#19]
I’d like to improve the quality of one of the banners on the website to enhance its visual appeal. This will help create a more engaging experience for users.

i can make the same banner with improved quality using some tools,
![banner](https://github.com/user-attachments/assets/f6226823-e96d-40c9-85a6-b814d9be6a01)

Please assign this issue to me under gssoc-ext, hacktoberfest-accepted

**Comment by GVishnudhasan** [comment]
Assigned @AswaniBolisetti. Good luck.
