### ISSUE TITLE
Want to add " SOCIAL MEDIA ICONS '"  in the footer section 

### ISSUE THREAD

**Issue by Vaibhavkumar5158** [GVishnudhasan/NoDueProject#41]
Want to add " SOCIAL MEDIA ICONS '"  in the footer section 

![image](https://github.com/user-attachments/assets/27cbc94e-913f-4d78-a888-4e55420160f9)

I would like to  add footer section and different social media icons  so that it looks more attractive and change the color whenever the cursor moves there.

Pls add GSSOC EXTD'24 and HACKTOBERFEST Badge and level .
@GVishnudhasan 

Thank you, looking forward to contribute .

**Comment by GVishnudhasan** [comment]
Duplicate #17.
