### ISSUE TITLE
Implement Registration Page with Client and Server Validation.

### ISSUE THREAD

**Issue by saloni911** [GVishnudhasan/NoDueProject#73]
To improve the accuracy and quality of user data stored in the database, I propose implementing a registration page with both client-side and server-side validation. This will ensure that no incomplete or blank entries are submitted to the database.

**Comment by GVishnudhasan** [comment]
It is not needed. Signup is already there and its accessible only by admin

**Comment by saloni911** [comment]
Then we can add this validation to sign up page. since we are going to add that data to our database.
