### ISSUE TITLE
Fixing Alignment of the image

### ISSUE THREAD

**Issue by khwa04** [GVishnudhasan/NoDueProject#95]
i want to fix the alignment of the image on the home page ( Spacing on right side and left side is different).
![Screenshot 2024-10-13 153322](https://github.com/user-attachments/assets/04e77432-aeda-4df8-9a2e-af1340be604b)
Please assign this issue to me under GSSoC extnd and Hacktoberfest.

**Comment by GVishnudhasan** [comment]
It is already done.
